# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passgen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(418, 366)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../source/appicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color:  rgb(52, 50, 50);\n"
"color: #fff;\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 250, 411, 20))
        self.label.setStyleSheet("color: #fff;\n"
"font-size: 15px;\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 70, 381, 51))
        self.lineEdit.setStyleSheet(".QLineEdit {\n"
"    background: #c8edb2;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    width: 80%;\n"
"    outline: none;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    color: 2e312c;\n"
"}\n"
"\n"
".QLineEdit:hover {\n"
"    opacity: 0.9;\n"
"}\n"
"")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 140, 381, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(81, 161, 94);\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"    width: 80%;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#cbe7f5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6fa94c ;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 280, 311, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(81, 161, 94);\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"    width: 80%;\n"
"    font-size: 13px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#cbe7f5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6fa94c ;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(81, 161, 94);\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"    width: 80%;\n"
"    font-size: 13px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#cbe7f5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6fa94c ;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(81, 161, 94);\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"    width: 80%;\n"
"    font-size: 13px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#cbe7f5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6fa94c ;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 261, 41))
        self.label_2.setStyleSheet("color: #fff;\n"
"font-size: 13px;")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PassGenerator by S-Mamashin"))
        self.label.setText(_translate("Form", "Добро пожаловать! by S-Mamashin"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Здесь будет ваш пароль!"))
        self.pushButton.setText(_translate("Form", "Сгенерировать"))
        self.pushButton_2.setText(_translate("Form", "8 символов"))
        self.pushButton_4.setText(_translate("Form", "16 символов"))
        self.pushButton_3.setText(_translate("Form", "32 символа"))
        self.label_2.setText(_translate("Form", "Пароли никуда не передаются!<br> Исходный код доступен на <a style=\"color: pink; text-decoration: red underline;\"  href=\"https://github.com/SMamashin/PassGenerator\">GitHub</a>."))
